services:
  computer-use-demo:
    build:
      context: .
      dockerfile: computer-use.Dockerfile
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - XAUTHORITY=/home/computeruse/.Xauthority
    volumes:
      - $HOME/.anthropic:/home/computeruse/.anthropic
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5901:5901"
      - "8501:8501"
      - "6080:6080"
      - "8080:8080"
    networks:
      - app_net
    cap_add:
      - NET_ADMIN
    depends_on:
      - mitmproxy
  
  mitmproxy:
    build:
      context: .
      dockerfile: mitmproxy.Dockerfile
    volumes:
      - ./certs:/home/mitmproxy/.mitmproxy
      - ./mitmproxy_scripts:/scripts:ro
    command: mitmweb --mode regular --listen-port 8082 --showhost --script /scripts/add_headers.py --web-host 0.0.0.0
    cap_add:
      - NET_ADMIN
    networks:
      - app_net
    ports:
      - "8081:8081"

networks:
  app_net:
    driver: bridge